export interface CaseStudy {
  slug: string
  company: string
  industry: string
  tagline: string
  description: string
  logoUrl: string
  logoAlt: string
  brandColor: string
  metrics: { label: string; before: string; after: string }[]
  challenge: string
  solution: string
  results: string
  quote: string
  quoteName: string
  quoteTitle: string
}

export const caseStudies: CaseStudy[] = [
  {
    slug: 'national-debt-relief',
    company: 'National Debt Relief',
    industry: 'Financial Services',
    tagline: 'From 44 to 93 — full WCAG 2.2 AA compliance in 6 weeks',
    description:
      'National Debt Relief is one of the largest debt settlement companies in the US, serving over 500,000 customers with a suite of financial tools and a customer-facing portal.',
    logoUrl: '/logos/national-debt-relief.svg',
    logoAlt: 'National Debt Relief logo',
    brandColor: '#0074e0',
    metrics: [
      { label: 'Accessibility score', before: '44', after: '93' },
      { label: 'WCAG violations', before: '127', after: '14' },
      { label: 'Critical issues', before: '31', after: '0' },
      { label: 'Time to compliance', before: '—', after: '6 weeks' },
    ],
    challenge: `National Debt Relief's customer portal — used by hundreds of thousands of people navigating financial hardship — had 127 WCAG violations across 340 pages. With a growing number of ADA demand letters targeting financial services companies, their legal team flagged the site as high-risk. Screen reader users couldn't complete core flows: checking account status, uploading documents, or contacting their advisor.`,
    solution:
      'The team integrated Naive AI into their development workflow in a single afternoon. A full site crawl surfaced all 127 violations ranked by severity. Auto-remediation handled 71 issues instantly — missing alt text, unlabelled form fields, and insufficient color contrast. The remaining issues were assigned to developers with code-level fix suggestions and WCAG citations. CI/CD integration was set up so no new pull request could introduce a critical violation.',
    results:
      'Within 6 weeks, National Debt Relief reached a 93 accessibility score — up from 44 — and eliminated all 31 critical violations. Ongoing monitoring catches new issues within hours of deployment. The legal team now has a VPAT and audit trail ready for any regulatory inquiry. Their screen-reader-accessible checkout flow has seen a measurable improvement in task completion rates among users with disabilities.',
    quote:
      "We had no idea how broken our portal was for customers using screen readers. Naive AI showed us the full picture and helped us fix it faster than we thought possible.",
    quoteName: 'Arthur Khmura',
    quoteTitle: 'Co-President & COO, National Debt Relief',
  },
  {
    slug: 'singlecase',
    company: 'SingleCase',
    industry: 'Legal Practice Management',
    tagline: 'WCAG compliance shipped in 2 weeks — with zero developer backlog',
    description:
      'SingleCase is a cloud-based practice management platform built for law firms and legal professionals, offering AI-powered document drafting, billing automation, and integrated case management.',
    logoUrl: '/logos/singlecase.svg',
    logoAlt: 'SingleCase logo',
    brandColor: '#FF6B35',
    metrics: [
      { label: 'Accessibility score', before: '51', after: '88' },
      { label: 'WCAG violations', before: '84', after: '9' },
      { label: 'Issues auto-fixed', before: '—', after: '68' },
      { label: 'Time to fix', before: '—', after: '2 weeks' },
    ],
    challenge: `As SingleCase expanded into enterprise law firms, procurement teams began requiring WCAG 2.1 AA conformance as a condition of purchase. Their platform had never been formally audited, and a preliminary scan revealed 84 violations across their core case management and document interfaces. Attorneys with visual impairments couldn't reliably navigate the matter list, and keyboard-only users hit dead ends in the document editor.`,
    solution: `SingleCase used Naive AI to run a comprehensive audit across all 6 core product surfaces. The scanner identified violations by component and page, making it easy to batch-fix recurring issues across the entire app. Naive AI's auto-remediation resolved 68 of 84 issues — primarily ARIA labelling, focus management, and heading hierarchy — without touching product functionality. The remaining 16 required design changes, which were handed off with annotated Figma-ready specs.`,
    results:
      'SingleCase went from 51 to 88 in two weeks without a dedicated accessibility sprint. The VPAT generated by Naive AI was accepted by three enterprise prospects during procurement. They now run accessibility checks on every pull request, preventing regressions before they reach production. Two enterprise deals that had been stalled on compliance requirements were closed within a month of remediation.',
    quote:
      "Enterprise procurement kept blocking us on accessibility. Naive AI turned what felt like a six-month project into a two-week fix — and the VPAT it generated closed deals.",
    quoteName: 'Pavel Krkoška',
    quoteTitle: 'CEO, SingleCase',
  },
  {
    slug: 'gngr-labs',
    company: 'GNGR Labs',
    industry: 'Health & Wellness E-commerce',
    tagline: 'Checkout conversion up 12% after making the storefront accessible',
    description:
      'GNGR Labs is a direct-to-consumer wellness brand specialising in high-absorption turmeric and ginger shots, selling through their Shopify storefront to tens of thousands of customers worldwide.',
    logoUrl: '/logos/gngr-labs.svg',
    logoAlt: 'GNGR Labs logo',
    brandColor: '#E21D38',
    metrics: [
      { label: 'Accessibility score', before: '62', after: '97' },
      { label: 'WCAG violations', before: '53', after: '2' },
      { label: 'Checkout conversion', before: 'Baseline', after: '+12%' },
      { label: 'Widget users/month', before: '—', after: '1,200+' },
    ],
    challenge:
      "GNGR Labs noticed in their analytics that users with assistive technology had a dramatically higher cart abandonment rate than average — over 80% on the checkout page. Their storefront had 53 WCAG violations, and the product page's colour contrast failed at 1.8:1 — well below the required 4.5:1. Screen reader users couldn't interact with the quantity selector, and the \"Add to cart\" button had no accessible label.",
    solution:
      "GNGR Labs embedded the Naive AI accessibility widget on their storefront in under 10 minutes. The widget immediately gave customers with visual impairments tools to increase contrast, enlarge text, and stop animations. In parallel, the Naive AI scanner identified the 53 violations and auto-fixed 51 of them — including all contrast failures, missing button labels, and inaccessible form controls. The two remaining issues (a custom slider component) were resolved by their front-end developer using the provided code fix.",
    results:
      'GNGR Labs achieved a 97 accessibility score — up from 62. Checkout conversion among all users improved by 12%, driven largely by clearer button labels and a more navigable product page. Over 1,200 customers per month actively use the accessibility widget. The brand now leads their niche on accessibility, which has become a talking point in their sustainability and inclusivity marketing.',
    quote:
      "We didn't realise how many customers we were losing because our checkout was broken for screen reader users. Two weeks later, conversion was up 12%. That paid for years of Naive AI.",
    quoteName: 'Namik Soltan',
    quoteTitle: 'Founder & CEO, GNGR Labs',
  },
]

export function getCaseStudy(slug: string): CaseStudy | undefined {
  return caseStudies.find((c) => c.slug === slug)
}
